services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    develop:
      watch:
        - action: rebuild
          path: ./frontend/static
          target: /usr/share/nginx/html/static

  signalling:
    build:
      context: signalling
      dockerfile: Dockerfile
    ports:
      - "8443:8443"